"""Forecast-vs-actual plot, drawn from results/metrics.json alone.

Usage:
    m5-plots                            # after m5-backtest

Plots whole-store daily units over the walk-forward test windows: the actual sales and
each model's forecast, with fold boundaries marked. Every number comes from the
`store_daily_units` that m5-backtest recorded, so the image is regenerated by this
script and never edited by hand.
"""

from __future__ import annotations

import argparse
import json
from datetime import date, timedelta
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from m5 import config  # noqa: E402

# Drawn in this order; models missing from the report are skipped.
PLOT_MODELS = ["seasonal_naive", "ridge", "lightgbm", "xgboost"]
COLORS = {
    "seasonal_naive": "#9a9a9a",
    "ridge": "#d98c2b",
    "lightgbm": "#2f6fb0",
    "xgboost": "#3d9a5b",
}


def forecast_vs_actual(report: dict[str, Any], out: Path) -> Path:
    folds = report["folds"]
    days: list[date] = []
    for f in folds:
        start = date.fromisoformat(f["test_start_date"])
        days += [start + timedelta(days=i) for i in range(f["test_end_d"] - f["test_start_d"] + 1)]
    first_model = next(iter(report["models"].values()))
    actual = [v for r in first_model["folds"] for v in r["store_daily_units"]["actual"]]

    x = list(range(len(days)))
    fig, ax = plt.subplots(figsize=(12, 5), dpi=120)
    ax.plot(x, actual, color="black", linewidth=2.2, label="Actual", zorder=5)
    for name in [m for m in PLOT_MODELS if m in report["models"]]:
        model = report["models"][name]
        forecast = [v for r in model["folds"] for v in r["store_daily_units"]["forecast"]]
        ax.plot(
            x,
            forecast,
            color=COLORS[name],
            linewidth=1.4,
            label=f"{name} (mean WRMSSE {model['mean_wrmsse']:.3f})",
        )
    offset = 0
    for f in folds:
        length = f["test_end_d"] - f["test_start_d"] + 1
        if offset:
            ax.axvline(offset - 0.5, color="#666", linestyle="--", linewidth=0.8)
        ax.text(
            offset + (length - 1) / 2,
            1.01,
            f"Fold {f['fold']}",
            transform=ax.get_xaxis_transform(),
            ha="center",
            va="bottom",
            fontsize=9,
            color="#444",
        )
        offset += length
    ax.set_xticks(x[::7], [d.strftime("%b %d") for d in days[::7]])
    ax.set_xlim(-0.5, len(days) - 0.5)
    ax.set_title(
        f"Store {report['store_id']}: daily units sold, actual vs {report['horizon_days']}-day "
        "forecasts made at each fold's cutoff",
        pad=18,
    )
    ax.set_ylabel("Units sold (whole store)")
    ax.set_ylim(bottom=0)
    ax.grid(axis="y", alpha=0.3)
    ax.legend(loc="lower left", fontsize=9, framealpha=0.9)
    fig.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out)
    plt.close(fig)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", type=Path, default=config.RESULTS_DIR)
    args = parser.parse_args(argv)
    report = json.loads((args.results_dir / "metrics.json").read_text())
    out = args.results_dir / f"forecast_vs_actual_{report['store_id']}.png"
    print(f"Wrote {forecast_vs_actual(report, out)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
